url: https://github.com/IamRaviMaurya
baseurl: ""
# Site settings
title: Bageshwar Dham Maharastra Seva Samiti
email: bageshwardhammaharastrasamiti@gmail.com
description: "Dhirendra Krishna Shastri also known as Bageshwar Dham Sarkar, is an Indian self-styled godman. He is the peethadhishwar of Bageshwar Dham, a religious Hindu site in Madhya Pradesh, India."


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://x.com/bageshwardhams
  - title: facebook
    url: https://www.facebook.com/bageshwardhamsarkarofficial/
  - title: instagram
    url: https://www.instagram.com/bageshwardhammaharashtra/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty